version: "2.0"

services:
    mongodb:
    image : mongo
    container_name: mongodb
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
    - 27017:27017
    restart: unless-stopped