version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "psimplify-b"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rohj1rx81rhi"
s3_prefix = "psimplify-b"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectId=\"\" CodeDeployRole=\"\" Stage=\"\""
